[workspace]
resolver = "3"
members = ["bin/ztreamerd", "crates/indexer", "crates/node", "crates/protocol", "crates/service"]

[workspace.dependencies]
zakura-chain = { git = "https://github.com/zakura-core/zakura.git", tag = "v1.5.1" }
zakura-network = { git = "https://github.com/zakura-core/zakura.git", tag = "v1.5.1" }
zakura-state = { git = "https://github.com/zakura-core/zakura.git", tag = "v1.5.1" }
zakura-test = { git = "https://github.com/zakura-core/zakura.git", tag = "v1.5.1" }
zakurad = { package = "zakura", git = "https://github.com/zakura-core/zakura.git", tag = "v1.5.1", default-features = false }
zakura-node-services = { git = "https://github.com/zakura-core/zakura.git", tag = "v1.5.1" }
