[package]
name = "ztreamer-node"
version = "0.0.1"
edition = "2024"

[dependencies]
color-eyre = { version = "0.6", default-features = false }
tower = { version = "0.4.13", features = ["buffer", "util"] }
zakura-chain.workspace = true
zakura-node-services.workspace = true
zakura-state = { workspace = true, features = ["indexer"] }
zakurad = { workspace = true, features = ["indexer"] }
